export enum OrderStatusEnum {
    UNASSIGNED = "UNASSIGNED",
    PARTIALLY_ASSIGNED = "PARTIALLY_ASSIGNED",
    VOIDED = "VOIDED",
    ASSIGNED = "ASSIGNED",
    COMPLETED = "COMPLETED",
    DELIVERED = "DELIVERED"
}
